### ISSUE TITLE
Example using Apache Beam Python SDK

### ISSUE THREAD

**Issue by Meosit** [aws-samples/amazon-managed-service-for-apache-flink-examples#54]
This repo is lacking an example of using Apache Beam Python SDK, it only contains Java Beam Application

**Comment by nicusX** [comment]
At the moment, Amazon Managed Service for Apache Flink does not support Apache Beam Python

**Comment by jimbobparsons** [comment]
@nicusX do you know if there is a recommended AWS service to run `Apache Beam Python SDK` code? I am looking to migrate some Dataflow pipelines to AWS
